require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HostgroupsController do

  # This should return the minimal set of attributes required to create a valid
  # Hostgroup. As you add validations to Hostgroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "host_name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HostgroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all hostgroups as @hostgroups" do
      hostgroup = Hostgroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:hostgroups).should eq([hostgroup])
    end
  end

  describe "GET show" do
    it "assigns the requested hostgroup as @hostgroup" do
      hostgroup = Hostgroup.create! valid_attributes
      get :show, {:id => hostgroup.to_param}, valid_session
      assigns(:hostgroup).should eq(hostgroup)
    end
  end

  describe "GET new" do
    it "assigns a new hostgroup as @hostgroup" do
      get :new, {}, valid_session
      assigns(:hostgroup).should be_a_new(Hostgroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested hostgroup as @hostgroup" do
      hostgroup = Hostgroup.create! valid_attributes
      get :edit, {:id => hostgroup.to_param}, valid_session
      assigns(:hostgroup).should eq(hostgroup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Hostgroup" do
        expect {
          post :create, {:hostgroup => valid_attributes}, valid_session
        }.to change(Hostgroup, :count).by(1)
      end

      it "assigns a newly created hostgroup as @hostgroup" do
        post :create, {:hostgroup => valid_attributes}, valid_session
        assigns(:hostgroup).should be_a(Hostgroup)
        assigns(:hostgroup).should be_persisted
      end

      it "redirects to the created hostgroup" do
        post :create, {:hostgroup => valid_attributes}, valid_session
        response.should redirect_to(Hostgroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hostgroup as @hostgroup" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hostgroup.any_instance.stub(:save).and_return(false)
        post :create, {:hostgroup => { "host_name" => "invalid value" }}, valid_session
        assigns(:hostgroup).should be_a_new(Hostgroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Hostgroup.any_instance.stub(:save).and_return(false)
        post :create, {:hostgroup => { "host_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hostgroup" do
        hostgroup = Hostgroup.create! valid_attributes
        # Assuming there are no other hostgroups in the database, this
        # specifies that the Hostgroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Hostgroup.any_instance.should_receive(:update_attributes).with({ "host_name" => "MyString" })
        put :update, {:id => hostgroup.to_param, :hostgroup => { "host_name" => "MyString" }}, valid_session
      end

      it "assigns the requested hostgroup as @hostgroup" do
        hostgroup = Hostgroup.create! valid_attributes
        put :update, {:id => hostgroup.to_param, :hostgroup => valid_attributes}, valid_session
        assigns(:hostgroup).should eq(hostgroup)
      end

      it "redirects to the hostgroup" do
        hostgroup = Hostgroup.create! valid_attributes
        put :update, {:id => hostgroup.to_param, :hostgroup => valid_attributes}, valid_session
        response.should redirect_to(hostgroup)
      end
    end

    describe "with invalid params" do
      it "assigns the hostgroup as @hostgroup" do
        hostgroup = Hostgroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hostgroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => hostgroup.to_param, :hostgroup => { "host_name" => "invalid value" }}, valid_session
        assigns(:hostgroup).should eq(hostgroup)
      end

      it "re-renders the 'edit' template" do
        hostgroup = Hostgroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Hostgroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => hostgroup.to_param, :hostgroup => { "host_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hostgroup" do
      hostgroup = Hostgroup.create! valid_attributes
      expect {
        delete :destroy, {:id => hostgroup.to_param}, valid_session
      }.to change(Hostgroup, :count).by(-1)
    end

    it "redirects to the hostgroups list" do
      hostgroup = Hostgroup.create! valid_attributes
      delete :destroy, {:id => hostgroup.to_param}, valid_session
      response.should redirect_to(hostgroups_url)
    end
  end

end
